default-timeout=5000
anchor=top-right
font=Inter Display 12
width=420
height=65

margin=10
outer-margin=0
padding=10,20

border-size=1
border-radius=16
max-icon-size=32

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false

[urgency=critical]
default-timeout=0
layer=overlay
# Adds a nice touch: use the red critical color from your Waybar
border-color=#ea6962FF

[summary~="Setup Wi-Fi"]
on-button-left=exec sh -c 'omarchy-notification-dismiss "Setup Wi-Fi"; omarchy-launch-wifi'

[summary~="Update System"]
on-button-left=exec sh -c 'omarchy-notification-dismiss "Update System"; omarchy-launch-floating-terminal-with-presentation omarchy-update'

[summary~="Learn Keybindings"]
on-button-left=exec sh -c 'omarchy-notification-dismiss "Learn Keybindings"; omarchy-menu-keybindings'

[summary~="Screenshot copied & saved"]
max-icon-size=80
format=<b>%s</b>\n%b