[manager]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true

[opener]
edit = [
	{ run = 'vim %*', block = true },
]

[preview]
image_quality = 90