source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

# --- BACKGROUND ---
background {
    monitor =
    path = ~/.config/omarchy/current/background
    color = $color
    blur_passes =1
    blur_size = 4
}
background {
    monitor = eDP-1
    path = ~/.config/omarchy/current/background
    color = $color
    blur_passes = 1
    blur_size = 1
}

# --- ANIMATIONS ---
animations {
    enabled = true
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    
    # Global Fades
    animation = fadeIn, 1, 4, overshot
    animation = fadeOut, 1, 4, overshot
    
    # Input Field Specific
    animation = inputFieldColors, 1, 5, overshot # Smooth color transitions
    animation = inputFieldWidth, 1, 5, overshot  # Subtle width bounce on focus
    animation = inputFieldDots, 1, 6, overshot   # Smooth dot appearance
}

# --- EDITORIAL CLOCK ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = $font_color
    font_size = 220
    font_family = Inter Display ExtraBold
    position = 80, -80
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $font_color
    font_size = 220
    font_family = Inter Display Light
    position = 80, -330
    halign = left
    valign = top
}

# --- DATE ---
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = $font_color
    font_size = 42
    font_family = Inter Display Thin
    position = 95, -640 
    halign = left
    valign = top
}

# --- INPUT FIELD ---
input-field {
    monitor = eDP-1
    size = 300, 120
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    
    # outer_color = rgba(0, 0, 0, 0) # Made transparent to avoid double-borders
    # inner_color = rgba(255, 255, 255, 0.2)
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    font_family = Inter Display 
    
    fade_on_empty = true
    rounding = 100 
    
    # Adaptive placeholder color
    placeholder_text = Welcome Back
    check_color = $check_color
    fail_color = rgb(204, 34, 34)

    position = 0, 0
    halign = center
    valign = center
}

# --- PROFILE IMAGE & NAME ---
image {
    monitor =
    path = ~/profile_image.jpg
    size = 200
    rounding = 60
    border_size = 3
    border_color = $font_color
    position = 0, 120
    halign = center
    valign = bottom
}

label {
    monitor =
    text = Prajwal Prathiksh
    font_size = 32
    font_family = Inter Display Light
    color = $font_color
    
    position = 0, 40
    halign = center
    valign = bottom
}


# --- MUSIC & STATUS ---
label {
    monitor = eDP-1
    text = cmd[update:2000] echo "$(~/.config/hypr/scripts/nowplaying.sh)" 
    color = $font_color
    font_size = 32
    font_family = Inter Display Light
    position = 80, 40
    halign = left
    valign = bottom
}

label {
    monitor = eDP-1
    text = cmd[update:5000] echo "$(~/.config/hypr/scripts/battery-status.sh)"
    color = $font_color
    font_size = 32
    font_family = Inter Display Light
    position = -80, 40
    halign = right
    valign = bottom
}