# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/tiling.conf
source = ~/.config/hypr/utilities.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

source = ~/.config/omarchy/current/theme/hyprland.conf

# Blur and transparency for SwayOSD
layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0.6, match:namespace swayosd
layerrule = animation popin 80%, match:namespace swayosd
 
# Blur and transparency for notifications
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0.5, match:namespace notifications
layerrule = animation popin 80%, match:namespace notifications

# Blur and transparency for Walker launcher
# layerrule = no_anim off, match:namespace walker
layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0.8, match:namespace walker

# layerrule = animation popin 80%, match:namespace walker
# layerrule = animation slide top, match:namespace walker

# Define terminal tag to style them uniformly
windowrule = tag +terminal, match:class (Alacritty|kitty|com.mitchellh.ghostty)
windowrule = tag -default-opacity, match:tag terminal
windowrule = opacity 0.95 0.7, match:tag terminal

# Apply default opacity after apps have had a chance to opt out
windowrule = opacity 0.95 0.6, match:tag default-opacity

