# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,2

# Primary Laptop Monitor
monitor=eDP-1,3000x1876@60.00,auto,2

# Work Monitor (Vertical, and to the left of the laptop)
monitor=desc:Dell Inc. DELL P2222H 56ST1P3, highres, -1080x-900, 1, transform, 1

# Home Monitor (Horizontal, and to the center top of the laptop)
monitor=desc:Lenovo Group Limited T32UD-40 V600CB4K, highres, -530x-1440, 1.5
